#!/usr/bin/env bash

pacd="/usr/bin/pacman -Syy"
pacg="/usr/bin/pacman -Su"

echo ""
echo -e "\033[46;30mStart\033[0m\n"

if [ $UID -eq 0 ]; then
    $pacd && $pacg
else
    echo -e "You Are \033[47;31mNOT ROOT\033[0m! Please Use \033[47;31m\"sudo pacu\"\033[0m."
fi

echo -e "\n\033[46;30mCompleted\033[0m"
echo ""
