* WARRING

*This configuration is only designed for my environment:*
#+BEGIN_SRC
Arch Linux x86_64
Awesome WM 4.0 and later
rxvt-unicode 9.2 and later
#+END_SRC
*If the user and my software environment is different, please select and customize files before use.*

The =mirrorlist= is a list of arch linux repository, but it's only useful in China.

* Features

This is my Awesome wm and rxvt-unicode configuraton.

It used my Pink theme and Arch Linux wallpaper.
Editor is emacs, web browser is firefox, others remain the default.

And my GNU nano editor configuration is in [[https://github.com/YuanPre/nanorc.git][YuanPre/nanorc]], Welcome to use and correction.

* Installation
To install, please make sure you have the above software and =git=,then run command in your shell:

#+BEGIN_SRC
git clone https://github.com/YuanPre/myconfig.git ~/myconfig
#+END_SRC

Then ,copy files you need in =~/myconfig= (like =cp ~/myconfig/.Xresources ~/=).

If you want to use my *all* configuration, run =cp ~/myconfig/.* ~/= and =sudo cp ~/myconfig/mirrorlist /etc/pacman.d= .

* Usage

+ Please see [[https://github.com/YuanPre/myconfig/blob/master/CUSTOM.org][CUSTOM.org]] for advice on customization.

+ Nothing in your clone directory ? Run =ls -a= to view the file. Because they are hidden files.\\
  Normally the configuration files are hidden files (with file name before "." ).

* Issues and Bug
Please open a Issues at this repository. I'm sorry I do not accept other ways.

*EOF*
