* WARRING

*This configuration is only designed for my environment:*
+ archlinux x86_64
+ Awesome WM 4.0 or later
+ URxvt 9.2 or later
*If your OS and/or software version is different, please test before use, and modify as needed.*
  
The =mirrorlist= is a list of archlinux software repository, but it's only useful in China.
  
* Features
  
This is my Awesome WM and URxvt configuraton.
  
  
It used my "=MX=" theme and archlinux wallpaper.

Default editor is emacs, web browser is firefox.

All other items are kept in default.
  
  
And my GNU nano editor configuration is in [[https://github.com/YuanPres/nanorc.git][YuanPres/nanorc]], Welcome to use and correction.

* Installation
To install, please make sure you have the above software and =git=,then run command in your shell:

#+BEGIN_SRC
git clone https://github.com/YuanPres/YuanConf.git ~/yuan
#+END_SRC

Then, copy files you need in =~/yuan= (like =cp ~/yuan/.Xresources ~/=).

If you want to use my *all* configuration, run =cp ~/yuan/.* ~/= and =sudo cp ~/yuan/mirrorlist /etc/pacman.d/= .
  
  
*Tips:* The =~/= is HOME directory.

* Usage

+ Please see [[https://github.com/YuanPres/YuanConf/blob/master/CUSTOM.org][CUSTOM.org]] for advice on customization.

+ Nothing in your clone directory ? Run =ls -a= to view the file. Because they are hidden files.\\
  Normally the configuration files are hidden files (with file name before "." ).

* Issues and Bug
  Please open a Issue in this: [[https://github.com/YuanPres/YuanConf/issues][YuanConf/issues]]. I'm sorry, I *DO NOT* accept any other way.

*EOF*
